# src/main/resources/application.properties

server.port=8080

# API keys
omdb.api.key=e1165b7
tmdb.api.key=ad9ef364c92af91a3e8844909044f8f7

spring.datasource.url=jdbc:h2:mem:moviesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true